### ISSUE TITLE
HTTP/2 documents need 'resources'

### ISSUE THREAD

**Issue by danyork** [InternetSociety/ose-documentation#19]
We need to add a **Resources** section to each of the HTTP/2 documents (`ose-web-http2-*`) that lists:

- the RFC(s) defining HTTP/2
- any outstanding tutorials on HTTP/2 that would help someone understand more (for example, does the Mozilla developer network have something good?)

**Comment by JohnS347** [comment]
https://tools.ietf.org/html/rfc7540
https://http2.github.io/

https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Evolution_of_HTTP#HTTP2_%E2%80%93_A_protocol_for_greater_performance
https://developers.google.com/web/fundamentals/performance/http2
https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices

**Comment by danyork** [comment]
@JohnS347 - Thank you for finding those resources! I included several of those.
